create table public.user_roles (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  department_id uuid null,
  project_id uuid not null,
  role public.app_role not null,
  constraint user_roles_pkey primary key (id),
  constraint user_roles_user_id_role_key unique (user_id, role),
  constraint user_roles_department_id_fkey foreign KEY (department_id) references departments (department_id),
  constraint user_roles_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;